Write a function so that the columns of the output matrix are powers of the input vector. 
The order of the powers is determined by the increasing boolean argument. Specifically, when  increasing is False, the i-th output column is the input vector raised element-wise to the power  of N - i - 1.


In [2]:
import numpy as np
# single line input array
x = np.array([1, 2, 3, 5])
# input vector
N = 3
np.vander(x, N, increasing=False) #with increasing boolean as False

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

In [3]:
np.array([1, 2, 3, 5])

array([1, 2, 3, 5])

In [4]:
np.vander(x,2, increasing=True) #with increasing boolean as True

array([[1, 1],
       [1, 2],
       [1, 3],
       [1, 5]])

In [5]:
import inspect
lines = inspect.getsource(np.vander)
print(lines)

@array_function_dispatch(_vander_dispatcher)
def vander(x, N=None, increasing=False):
    """
    Generate a Vandermonde matrix.

    The columns of the output matrix are powers of the input vector. The
    order of the powers is determined by the `increasing` boolean argument.
    Specifically, when `increasing` is False, the `i`-th output column is
    the input vector raised element-wise to the power of ``N - i - 1``. Such
    a matrix with a geometric progression in each row is named for Alexandre-
    Theophile Vandermonde.

    Parameters
    ----------
    x : array_like
        1-D input array.
    N : int, optional
        Number of columns in the output.  If `N` is not specified, a square
        array is returned (``N = len(x)``).
    increasing : bool, optional
        Order of the powers of the columns.  If True, the powers increase
        from left to right, if False (the default) they are reversed.

        .. versionadded:: 1.9.0

    Returns
    -------
    out : ndar

Write a function to find moving average in an array over a window:  Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [6]:
def mov_avg_val(mylist, N):
    cumsum, moving_aves = [0], []
    for i, x in enumerate(mylist, 1):
        cumsum.append(cumsum[i-1] + x) # summing up all the values one by one and appending the list
        if i>=N:
            moving_ave = round(((cumsum[i] - cumsum[i-N])/N),2) #computing the moving average using temp array sum array cumsum
            #can do stuff with moving_ave here
            moving_aves.append(moving_ave) # listing the moving average as an single array
    print("Moving average values list: ", moving_aves)
    print("Length of the list l-N+1: ", len(moving_aves))

In [8]:
mylist = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
N = 4

mov_avg_val(mylist,N)

Moving average values list:  [25.0, 35.0, 45.0, 55.0, 65.0, 75.0, 85.0]
Length of the list l-N+1:  7


In [9]:
mylist = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
N = 3

mov_avg_val(mylist,N)

Moving average values list:  [5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]
Length of the list l-N+1:  11
